### ISSUE TITLE
Request: Matrix (Matrix.org)

### ISSUE THREAD

**Issue by alicerunsonfedora** [jeremieb/social-symbols#12]
I would love to see a symbol for the [Matrix protocol/Matrix Foundation](https://matrix.org) to be able to reference it in my app, since there are some cases where `Text("[m]")` doesn't work well for an image in a label...

Logos are available at https://github.com/vector-im/logos.

**Comment by jeremieb** [comment]
That's a good idea and will add this as soon as possible. ;-)

**Comment by jeremieb** [comment]
Delivered in 1.0.8 release
