### ISSUE TITLE
Any plans to change the Twitter icon to X?

### ISSUE THREAD

**Issue by rampatra** [jeremieb/social-symbols#20]
Thanks for this package. Just had a small request about the updated Twitter icon.

**Comment by jeremieb** [comment]
Good idea, will add this to the backlog 😅

**Comment by rampatra** [comment]
Let me help you a bit. I have created the SF Symbol here: https://github.com/rampatra/assets/tree/main/SFSymbols. However, I have not created variations of it for ultrathin, bold, etc.

And, the logo itself can be found here: https://about.twitter.com/content/dam/about-twitter/x/brand-toolkit/x-logo.zip

**Comment by jeremieb** [comment]
I used the SVG as well. I'm not changing the logo weight for staying compliant with all those brands guideline, otherwise it's a risk of having them asking me to remove it from the library.

Thanks for your help and suggestion. ☺️
