### ISSUE TITLE
Request: TikTok

### ISSUE THREAD

**Issue by KlemensStrasser** [jeremieb/social-symbols#23]

**Comment by jeremieb** [comment]
![TikTok_logo](https://github.com/jeremieb/social-symbols/assets/736246/6df3e1a9-1e91-4762-b9c0-d73e1aa10e58)
![logo-tiktok-svgrepo-com](https://github.com/jeremieb/social-symbols/assets/736246/1bac0b73-951c-4fc4-8aee-297f74c088ed)

**Comment by jeremieb** [comment]
Done
