### ISSUE TITLE
Request: Twitter

### ISSUE THREAD

**Issue by Dean151** [jeremieb/social-symbols#5]
Hey!

I know it's maybe not the most loved social network right now, but it'd be awesome to have the following additions:
- twitter
- twitter.fill

Thanks for this repository. It was really missing out there!

**Comment by jeremieb** [comment]
I will have to think about it for this one and don't really want to support this platform anymore (I've been using Twitter for 15 years...). 😓

**Comment by jeremieb** [comment]
Done
